# Site settings
title: TIL
description: 공부한 것, 경험한 것을 기록하는 메모장
url: https://kwonjihyeon-dev.github.io
baseurl: /TIL

# Theme
remote_theme: jeffreytse/jekyll-theme-yat

# Plugins
plugins:
    - jekyll-remote-theme
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Permalink
permalink: pretty

# Author
title: hyeonnny_log
email: kjh2868@gmail.com
author: kwonjihyeon-dev

# Yat 테마 설정
yat:
  date_format: "%Y-%m-%d"

# 네비게이션 메뉴
header_pages:
    - index.md
    - architecture/index.md
    - cs/index.md
    - library/index.md
    - react/index.md
    - about.md

# 컬러 설정 (light / dark)
# color_scheme: dark

# 테마 컬러 커스터마이징 (주석 해제 후 사용)
# accent_color: "#268bd2"

# 사이드바 설정
toc: true

# Defaults
defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: post
    - scope:
          path: ''
          type: 'pages'
      values:
          layout: post
